### ISSUE TITLE
Implementar um tracker de combate

### ISSUE THREAD

**Issue by Seisaku** [Seisaku/RRPG#34]
- [ ] Reunir regras para definição de ordem
- [ ] Manter lista de NPCs envolvidos no combate
- [ ] Solicitar automaticamente todas as rolagens de iniciativa e descrever resultado
- [ ] Criar um componente de tracker para manter esse controle (similar ao tracker)
- [ ] Ao terminar o turno (e iniciar o próximo) repetir e reordenar
